spring:
  config:
    import: optional:file:secrets.properties

  application:
    name: oficinadasmeninas

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

storage:
  type: s3
  s3:
    endpoint: ${S3_ENDPOINT}
    region: ${S3_REGION}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket: ${S3_BUCKET}
    path-style-access: ${S3_PATH_STYLE:true}
